version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    networks:
      - web
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:v1.12.1
    depends_on:
      - nginx-proxy
    environment:
      - NGINX_PROXY_GEN_CONTAINER=nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - web
    restart: always
  www:
    image: nginx
    restart: always
    expose:
      - "80"
    volumes:
      - ./www:/usr/share/nginx/html:ro
    networks:
      - web  
    environment:
      - VIRTUAL_HOST=leogaray.com.ar,www.leogaray.com.ar
      - LETSENCRYPT_HOST=leogaray.com.ar,www.leogaray.com.ar
      - LETSENCRYPT_EMAIL=leo.garay9@gmail.com
  www-2:
    image: nginx
    restart: always
    expose:
      - "80"
    volumes:
      - ./www2:/usr/share/nginx/html:ro
    networks:
      - web    
    environment:
      - VIRTUAL_HOST=admin.leogaray.com.ar
      - LETSENCRYPT_HOST=admin.leogaray.com.ar
      - LETSENCRYPT_EMAIL=leo.garay9@gmail.com
volumes: 
  certs:
  html:
  vhostd:
networks:
  web:
    external: true