# Imagen Base
  FROM debian:8.7

  RUN apt-get update && apt-get install -y  

    RUN apt-get -y install software-properties-common mc nano 
    RUN apt-get -y install apache2 libapache2-mod-php5 php5-cli php5-pgsql php5-gd php5-curl php5-xsl 
    RUN apt-get -y install php5-mcrypt
# Configuración de apache
  COPY php.ini /etc/php5/apache2/php.ini
  COPY php.ini /etc/php5/cli/php.ini

  RUN a2enmod rewrite
  RUN a2enmod setenvif  

  EXPOSE 80

  CMD /usr/sbin/apache2ctl -D FOREGROUND  
